### ISSUE TITLE
After restarting, the changed settings in "developer settings" are reset.

### ISSUE THREAD

**Issue by lkchx123** [MustardChef/WSABuilds#16]
<img src="https://user-images.githubusercontent.com/46598881/218376346-626b76a9-360e-4036-9888-bca7863b0c2c.png" width="700px">
Restart after change, it is restored to 438.
<img src="https://user-images.githubusercontent.com/46598881/218376578-db69ff32-7121-4ced-a4d4-4ea28baf7829.png" width="250px">

The version is<img src="https://user-images.githubusercontent.com/46598881/218378017-30df139a-0780-48f0-8011-5038d6305b60.png" width="500px">

By the way, the language displayed in the "Windows Subsystem for Android Settings" window has changed to English after update. How to change the language?

**Comment by MustardChef** [comment]
- **The DPI changing back to 438 is normal. The fix is to change the DPI permanently in /vendor/build.prop using root access (through Magisk and text editor with root access)**
- **The language changed back to english, because there was a problem with the extraction of the language files when extracted WSA from the .msix bundles when building. I will update the file in Releases so that it does include this.**

### Change DPI on WSA.​
Changing DPI is one of the most useful build.prop for Android users. DPI refers to the Density Independent on the emulated device. You can find many apps in Google Playstore to change this setting but here you can directly tweak DPI on Android. If you set high amount of value in DPI then the output is smaller UI, smaller texts, smaller icons.

If you set low DPI then the output is a larger UI, larger texts, and larger icons. Always set a perfect DPI otherwise you can’t operate WSA. Add the following line to the end of the /vendor/build.prop.

ro.sf.lcd_density=XXX

Here, XXX refers to the DPI Value. The values are a multiple of 160, That is, 160, 320, 480, 640, etc. XXX replace with a value you like.

**Comment by lkchx123** [comment]
> * **The DPI changing back to 438 is normal. The fix is to change the DPI permanently in /vendor/build.prop using root access (through Magisk and text editor with root access)**
> * **The language changed back to English, because there was a problem with the extraction of the language files when WSA was extracted from the .msix bundles. I will update the file in Releases so that it does include the language files.**
> 
> ### Change DPI on WSA.​
> Changing DPI is one of the most useful build.prop for Android users. DPI refers to the Density Independent on the emulated device. You can find many apps in Google Playstore to change this setting but here you can directly tweak DPI on Android. If you set high amount of value in DPI then the output is smaller UI, smaller texts, smaller icons.
> 
> If you set low DPI then the output is a larger UI, larger texts, and larger icons. Always set a perfect DPI otherwise you can’t operate WSA. Add the following line to the end of the /vendor/build.prop.
> 
> ro.sf.lcd_density=XXX
> 
> Here, XXX refers to the DPI Value. The values are a multiple of 160, That is, 160, 320, 480, 640, etc. XXX replace with a value you like.

Thank you very much for your reply.😉

**Comment by MustardChef** [comment]
@lkchx123 can you please confim that the language issue is now fixed in the latest WSA update
