### ISSUE TITLE
WriteError in Powershell when reinstalling

### ISSUE THREAD

**Issue by IveMalfunctioned** [MustardChef/WSABuilds#18]
I had this installed on Windows 10. It stopped working all of a sudden, so I went to reinstall it, and this is what comes up in the Powershell console when running `Run.bat`: 

`Installing MagiskOnWSA...
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF9, Install failed. Please contact your software vendor.
                                                                                                                         Deployment operation progress: G:\Downloads\WSA_2301.40000.4.0_x64_Release-Nightly-with-magisk-831a398b.25206.-canary-M    Processing                                                                                                              [o                                                                                                           ]                                                                                                                              the command line Get-AppPackageLog -ActivityID da6b1296-41a6-0002-388b-72daa641d901
At G:\Downloads\WSA_2301.40000.4.0_x64_Release-Nightly-with-magisk-831a398b.25206.-canary-MindTheGapps-13.0-RemovedAmaz
on_Windows_10\WSA_2301.40000.4.0_x64_Release-Nightly-with-magisk-831a398b(25206)-canary-MindTheGapps-13.0-RemovedAmazon
\Install.ps1:102 char:1
+ Add-AppxPackage -ForceApplicationShutdown -ForceUpdateFromAnyVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (G:\Downloads\WS...ppxManifest.xml:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

All Done!
Press any key to exit`

It did not complete the install.

**Comment by MustardChef** [comment]
I would follow these steps:

**1. Ensure the partition/ drive you are installing from is NTFS**

**2. Redownload and reextract the WSA Build .zip (sometime the files can be corrupted dusing download and extraction)**

**3. Rename the folder to a shorter name  (WSA_2XXX.XXXXX.X.X_XXXX_Release-Nightly-with-magisk-XXXXXXX-XXXXXX-MindTheGapps-XX.X-RemovedAmazon ----> WSA)**

**4. Ensure that 'Run.bat' is run as Administrator**

If the problem still persists. please join the Discord, so that I can assist with the problem quicker than through Github issues.

**Comment by IveMalfunctioned** [comment]
That worked, thanks.
