### ISSUE TITLE
[REQUEST] Simulate lock screen

### ISSUE THREAD

**Issue by mid-kid** [MustardChef/WSABuilds#188]
### Describe your request | 描述您的要求

Some apps require a lock screen password to be configured. Would this be possible with WSABuilds or magisk?
See this, for example: https://www.reddit.com/r/Windows11/comments/t3ew2q/windows_subsystem_for_android_how_do_i_set_a_lock/

**Comment by BraINstinct0** [comment]
There used to be some Xposed modules up to Android 10, but I did not come across anything else since Android 11.
If my understanding is correct, the lock status check (and screenlock itself) is managed by KeyGuard - which has to be spoofed as being set in this case. I'm not sure about methods that can do this but certainly no non-root methods exist.

**Comment by mid-kid** [comment]
Well, thankfully WSABuilds is rooted, so that's always a possibility.

Why I asked here, though, is that WSABuilds has control over the base system, so perhaps it can be patched directly there?

**Comment by BraINstinct0** [comment]
If there's a method for rooted systems, then yes
But the problem is, I've yet to see one correctly working.
If you can find it, (I doubt it'll be included by default but) it can be added to your setup
