### ISSUE TITLE
[REQUEST] Add the AuroraStore

### ISSUE THREAD

**Issue by ElsAr4e** [MustardChef/WSABuilds#368]
### Describe your request

Please include the AuroaStore (https://gitlab.com/AuroraOSS/AuroraStore) by default

**Comment by MustardChef** [comment]
This project is now in Long Term Support (LTS), no more requests will be fulfilled.
Sorry for any inconvenience caused.

**Comment by ElsAr4e** [comment]
Would it be really difficult to add the AuroraStore? I thought it's just including an .apk file that will be automatically installed?

And even if this project is LTS this should not make cost much time?

**Comment by MustardChef** [comment]
> Would it be really difficult to add the AuroraStore? I thought it's just including an .apk file that will be automatically installed?
> 
> And even if this project is LTS this should not make cost much time?

The reverse is also true. It should be noted that Aurora Store can be installed by a user after installation of WSA. A process that takes a minute or two, and should not cost you much time. 

However, modifying the workflow and other files to accommodate your request would take much longer. The demerits, spending time modifying the workflow and other files in order to add releases with AuroraStore, outweigh the merits.

**Comment by ElsAr4e** [comment]
> The reverse is also true.

Thanks for your answer. Good to know! Is there a tutorial how I can install apk using the WSABuilds? And/or could you add a tutorial in the README (so you can use any apk to install any app)?

**Comment by MustardChef** [comment]
> > The reverse is also true.
> 
> Thanks for your answer. Good to know! Is there a tutorial how I can install apk using the WSABuilds? And/or could you add a tutorial in the README (so you can use any apk to install any app)?

[Refer to this guide](https://github.com/MustardChef/WSABuilds/blob/master/Documentation/Usage%20Guides/Sideloading%20Guides/Sideloading.md)

**Comment by ElsAr4e** [comment]
Thank you for the information and your answer!
