### ISSUE TITLE
[REQUEST]Non-Magisk Variation

### ISSUE THREAD

**Issue by Cavemanchess** [MustardChef/WSABuilds#443]
### Describe your request

I've tried the various ways to hide Magisk, but my company blocks Android connections with Magisk installed - the company automatically assumes Root. I don't know what's triggering this, but hiding Magisk or using other addins that assist in hiding Magisk has not solved the issue.

Is there an up-to-date (Android 13) variant without Magisk available?

**Comment by MustardChef** [comment]
Please use these builds instead:
https://github.com/MustardChef/WSABuilds/releases/tag/Windows_11_2311.40000.5.0

**Comment by d1Bihkte** [comment]
@MustardChef I have few problems.

1. I installed [WSA_2407.40000.0.0_x64_Release-Nightly-GApps-13.0-NoAmazon_Windows_10 build](https://github.com/MustardChef/WSABuilds/releases/download/Windows_10_2407.40000.0.0/WSA_2407.40000.0.0_x64_Release-Nightly-GApps-13.0-NoAmazon_Windows_10.7z) on windows 10 and it has magisk. This [payment app](https://play.google.com/store/apps/details?id=com.paymentservices.upay) detects root and i don't know how to hide root. If not possible to hide, do you have a suitable build for windows 10?

<details>
<summary>screenshot</summary>

![app](https://github.com/user-attachments/assets/73ac35b4-cb70-4af0-8e2e-b4bd9658914a)

</details>

2. I can't install [skype app](https://play.google.com/store/apps/details?id=com.skype.raider) on WSA. I tried to install through aurora store and apk. It show error message about something related amazon is missing but i do not want to install a build that contain amazon app store  (sorry, i dont have a way to reproduce it due to (3) for copy the error message.
3. I already used WSA on windows 10 for a month, installed and used 43 apps. Today i turned on windows and opened apps, WSA only keep showing "Staring windows subsystem for android" window. I turned off WSA and opened few apps again, restarted device but the problem still persist. Is there any way for fix this without reinstall WSA?
