### ISSUE TITLE
[BUG 2304.40000.4.0] Magisk not installed

### ISSUE THREAD

**Issue by Mitia99** [MustardChef/WSABuilds#79]
### Describe the bug | 描述一下这个错误

Dear dev,

After the fix for #76 

I noticed that Magisk is not installed after a clean installation of 
https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2304.40000.4.0/WSA_2304.40000.4.0_x64_Release-Nightly-with-magisk-d0c93842.26101.-canary-MindTheGapps-13.0-RemovedAmazon.zip

Thanks,

### Steps to reproduce the issue | 重现该问题的步骤

Install

https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2304.40000.4.0/WSA_2304.40000.4.0_x64_Release-Nightly-with-magisk-d0c93842.26101.-canary-MindTheGapps-13.0-RemovedAmazon.zip

### Expected behaviour | 预期的行为

Magisk installed

### Downloaded Build Of WSA | 已下载的WSA版本

https://github.com/MustardChef/WSABuilds/releases/download/Windows_11_2304.40000.4.0/WSA_2304.40000.4.0_x64_Release-Nightly-with-magisk-d0c93842.26101.-canary-MindTheGapps-13.0-RemovedAmazon.zip

### Windows build number | Windows构建号

Windows 11 22H2 build 22621.1702

### PC Specification | 个人电脑规格

Matebook E
I5 11th
RAM 16Go
512Go

**Comment by MustardChef** [comment]
@Mitia99 Known issue. It is an issue with Magisk and not WSA and MagiskOnWSALocal. The solution is to sideload the manager, since Magisk has been installed, but the manager has not been. Once the Manager is installed, it should work as normal.

Issue in question: 
https://github.com/LSPosed/MagiskOnWSALocal/issues/493
and 
https://github.com/LSPosed/MagiskOnWSALocal/issues/535#issuecomment-1546827295

**Comment by Mitia99** [comment]
I reinstalled WSA again and Magisk was installed. I'll close the issue then.
